### ISSUE TITLE
Chrome error and list of IMEs and what we should expect?

### ISSUE THREAD

**Issue by talltyler** [w3c/edit-context#105]
I'm noticing a bug in the Chrome EditContext API when long pressing the 'o' key on a mac to bring up the menu that shows 'òóôöǒœøõō' that resets the selectionStart to 0 and appends the new character rather than replacing the one at the current selectionStart.

Is there a list of IMEs and methods to tests them so I can write a more comprehensive bug report of what isn't working?
And where is the best place to report this, if not here?

**Comment by dandclark** [comment]
For things like this that look like bugs in the Chromium implementation (rather than API design feedback), [crbug.com](https://crbug.com/) is the right place to file issues.

This one sounds a lot like https://issues.chromium.org/issues/40933404#comment5. The fix for that ships in Chrome 128. If you can check the chrome://version number and include that in the bug report, that would help confirm. If it no longer repros in Chrome version 128, then it's almost definitely the same issue.

Thanks for checking into this!
