### ISSUE TITLE
EditContext: "it is focusable" is underdefined

### ISSUE THREAD

**Issue by annevk** [w3c/edit-context#21]
There are other features that can make an element focusable, such as `tabindex`. Ideally this is defined in terms of HTML's focus concepts as the current text is rather abstract and leaves a lot of guessing to implementers.

cc @domenic

**Comment by dandclark** [comment]
This is resolved in the [newer version of the spec](https://w3c.github.io/edit-context/#editcontext-model:~:text=Associating%20an%20EditContext%20to%20an%20element%20makes%20that%20element%20an%20editing%20host).

Rather than talking about focusability directly, the spec now says that “Associating an `EditContext` to an element makes that element an [editing host](https://html.spec.whatwg.org/multipage/interaction.html#editing-host)”.

The HTML spec definition of [editing host]([https://html.spec.whatwg.org/multipage/interaction.html#editing-host](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhtml.spec.whatwg.org%2Fmultipage%2Finteraction.html%23editing-host&data=05%7C01%7Cdaniec%40microsoft.com%7C87b3ac84af4544c7f91e08db4dc7958c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638189291854209899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sDutiKJ9JVQzhJnT97x6pftLbyTASSJmrBbQ4LnJe%2FU%3D&reserved=0)) will have to be updated to include EditContext, but its handling of focusability should cover the EditContext case.

I'll close out this issue but please reopen if you think this isn’t sufficient.

**Comment by annevk** [comment]
I cannot reopen.

What happens if the element is already an editing host? (Though perhaps this should be a separate issue.)

**Comment by dandclark** [comment]
Good question, I think it deserves its own issue: https://github.com/w3c/edit-context/issues/38
