### ISSUE TITLE
Should the methods of EditContext throw an exception if they abort due to not activated?

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/edit-context#26]
The methods of `EditContext` are defined their behavior as

> 1.  If the EditContext is not activated, abort these steps. 

But this is unclear whether an exception should be thrown or silently do nothing.

**Comment by dandclark** [comment]
This is an old issue but the question is still relevant, and we should prioritize resolving it.
The 4 methods that have this behavior are `updateText()`, `updateSelection()`, `updateSelectionBounds()`, `updateControlBounds()`, and `updateCharacterBounds()`


There's a third option I'd also like to consider, which is that we could just let the methods run normally even if the EditContext is not active. I think that is actually the more desirable behavior. Consider a page with multiple editable forms each implemented with EditContext, and the page has a single button to clear all forms. The page should not be required to set focus on each form in order to clear its text state.

The implementations of these methods don't fire any events, they're just a state update. So allowing them to function on a non-active EditContext should not introduce any complications.

**Comment by dandclark** [comment]
Bot posted the minutes from the wrong topic. Here are the correct minutes from the 2023-10-12 WG meeting:

> 8:40 AM <sanketj_> dandclark: Spec mentions that updateText and similar method all should abort early if EditContext is not active.
8:41 AM <sanketj_> dandclark: Chromium does not implement that way, does not abort if EditContext is not active.
8:41 AM <sanketj_> dandclark: Seems unnecessary to abort, and maybe not desirable.
8:41 AM <johanneswilm> q+
8:42 AM <sanketj_> johanneswilm: Agree not desirable. Requiring focus seems not as convenient.
8:43 AM <sanketj_> Resolution: Accept proposal.
