### ISSUE TITLE
Some thoughts on accessibility

### ISSUE THREAD

**Issue by travisleithead** [w3c/edit-context#6]
This issue was transferred from https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/180

@kbabbitt opened this issue on 2020-01-28

@BoCupp-Microsoft and I had a brief chat about accessibility implications of EditContext that I wanted to follow up on. The "Open Issues" page references AOM, but I don't think it's needed. I think instead, if we give the browser enough information to map an EditContext into its accessibility view of the DOM, a lot of existing support will just work.

The explainer mentions:
> * The coordinates of the selection and of a logically editable element so that UI relating to text input can be appropriately positioned.

What if we upgraded this a bit and linked an EditContext to a DOM element, without coupling it back to the content of that element? That would allow the browser to relate the EditContext to the rest of the document. With that information:
* The browser would understand how to integrate an EditContext into tab order
* An EditContext could become just another node in the browser's accessibility tree representation, meaning assistive technologies don't need to have any special understanding of how to work with an EditContext

Apart from that, I think the pieces you would need to make EditContext accessible is already covered by the explainer:
- Which EditContext, if any, currently has input focus
- Selection / caret position
- Style / annotation / highlight information
- Consumption of input events (accessibility APIs can generate these too, but they would be mapped to DOM events)

---

@travisleithead commented on 2020-02-12

> Q: Is this possible to hook-up to the existing accessibility tree?

@kbabbitt commented on 2020-04-15

>> Q: Is this possible to hook-up to the existing accessibility tree?
>
>That's what I'm hoping for with my suggestion :)

**Comment by dandclark** [comment]
I think this feedback was based on an earlier version of EditContext where there wasn't a well-defined association with a given DOM element.

Now, an EditContext must have an [associated element](https://w3c.github.io/edit-context/#dfn-associated-element) to receive input, which should address the concerns here. The DOM contents of the element, constituting the editor view, will be visible in the appropriate order in the accessibility tree, as well as the user's selection.

The partial exception is when the editor is implemented in a `<canvas>`, in which case the contents of the editable region will not be visible to accessibility since it can't see the `<canvas>` contents. The accessibility story here is no better and no worse than `<canvas>`-based editors today, where authors need to implement a separate hidden HTML-view of the editor contents for accessibility. Future proposals may make this easier, but it is out of scope for EditContext.
