### ISSUE TITLE
Spec defines 'double' in a way that collides with WebIDL

### ISSUE THREAD

**Issue by hober** [w3c/edit-context#89]
Maybe use a different term?

I'm seeing this Bikeshed error on an unrelated document:

```
LINK ERROR: Multiple possible 'double' idl refs.
Arbitrarily chose https://w3c.github.io/edit-context/#dom-underlinestyle-double
To auto-select one of the following refs, insert one of these lines into a <pre class=link-defaults> block:
spec:edit-context; type:enum-value; text:double
spec:webidl; type:interface; text:double
{{double}}
```

**Comment by dandclark** [comment]
@snianu or @alexkeng do you know where "double" would actually be needed? In Chromium at least it doesn't look like "double" is a possible IME underline style ([link](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/ime/ime_text_span.h;l=41;drc=20cb8070fa5e69291d4a6ae626c55435a8d00802)): 
```c++
  enum class UnderlineStyle {
    kNone,
    kSolid,
    kDot,
    kDash,
    kSquiggle,
  };
```
I'm wondering if this can just be removed...but maybe you remember some context for why it's an option in the spec? Is it used with IMEs in other browsers?

**Comment by dandclark** [comment]
I spoke with @snianu about this today. `double` was added to EditContext early on because it was expected to be used by a planned Windows feature, but that feature never landed. So at least for now there is no known use for it. I will Agenda+ to discuss next WG meeting but I expect that this can simply be removed.
