### ISSUE TITLE
Need to specify which input types are handled by EditContext

### ISSUE THREAD

**Issue by dandclark** [w3c/edit-context#94]
EditContext doesn't fire `textupdate` for every `inputType`. E.g. EditContext will fire `textupdate` for `"insertText"` but not for `"formatBold"`. However this behavior doesn't actually seem to be in the spec.

It seems that it should be added to either the EditContext bullet point of https://w3c.github.io/input-events/#event-definitions or to https://w3c.github.io/edit-context/#dfn-handle-input-for-editcontext.

While we work this out, it would be a good time to review that we're sending the correct `inputType`s to EditContext.
In the Chromium's implementation the list is:
- `"insertText"`
- `"deleteContent"`·
- `"deleteWordBackward"`
- `"deleteWordForward"`
- `"deleteContentBackward"`
- `"deleteContentForward"`

The intention here is that EditContext only handles changes that make sense for plain text, so things like bold/italic/underline are excluded. An interesting case to consider is that currently the Enter key is not handled by EditContext, because formatting for commands like `"insertLineBreak"` or `"insertParagraph"` can be nontrivial in rich text.

**Comment by johanneswilm** [comment]
As I understand the difference between an input type that is on this list and one that is not: 

1. If a specific input type is on the list, then the browser will by default update the `text state` of the `EditContext` according to the default behavior of the browser. If the web author does not want this to happen, they need to `preventDefault` the before input event and update the `text state` manually.

2. If an input type is not on the list, then the `text state` will not be updated automatically and the web author will have to update it manually if needed.

A lot fo the input types will not normally lead to an update to the `text state` anyway because they deal with formatting or similar and so there is no need for manual update of the `text state` either.

The selection of input types may seem a bit arbitrary, almost no matter what one chooses. It looks like the criteria that has been used for this selection was:

* Remove all the input types that deal with formatting.
* Remove all the input types that deal with insertion of non-text content (lists, horizontal ruler, link).
* Remove all the input types that deal with the clipboard or clipboard-alike (paste/cut/yank/drop/drag).
* Remove all the input types that have to do with physical placement of content on the screen (softline deletions).
* Remove all the input types that deal with the document history.
* Remove all the input types that include additonal UI (spell checkers, LLMs, etc.)

This selection follows a certain logic. However, this still gives me a few more input types than what are currently selected, namely:

* `"insertLineBreak"`/`"insertParagraph"` - Will there be a difference between paragraph and line break in the `text state` of the `EditContext`? Or will the default for both just be the insertion of `\n`?
* `"insertTranspose"` - I wonder if the default is not best left to the browser as figuring out which were the last two characters entered and make them switch places could be quite complex in JavaScript. Note: transposing characters is not supported on most platforms.
* `"deleteHardLineBackward"`/`"deleteHardLineForward"` - If these are just deleting until the next `\n` in the `text state`, then they seem fairly similar to `"deleteWordBackward"`/`"deleteWordForward"`.

Question: Would it be an option to not have any of the input types auto-update the `text state` to make it consistent? Or would that be impossible tdue to IME, etc.?

**Comment by dandclark** [comment]
Minutes from the April WG meeting:

> [17:03] <smaug> dandclark: we did discuss about this last time
[17:04] <smaug> EditContext handles certain kinds of input, but doesn't handle formatting kinds of cases
[17:04] <smaug> need to document better which should be handled
[17:05] <smaug> the bullet points johanneswilm listed in the issue are a good starting point
[17:06] <smaug> insertLineBreak and such can be complicated if the selection isn't collapsed
[17:07] <smaug> EditContext wouldn't ever fire event for the cases when the internal state doesn't change
[17:08] <johanneswilm> q+
[17:08] <smaug> dandclark: which commands should be handled automatically and which shouldn't?
[17:10] --> sanketj_ (~uid392014@9347813c.public.cloak) has joined this channel.
[17:10] <smaug> johanneswilm: In many cases it would be good that browser takes care of the command. Author is still able to decide by cancelling beforeinput, correct?
[17:11] <dandclark> q+
[17:11] <smaug> johanneswilm: is entering linebreak complicated also in text buffer case?
[17:11] <smaug> dandclark: yeah, beforeinput can be cancelled
[17:12] <smaug> dandclark: some of these commands rely on formatting context, I think
[17:13] <smaug> ...which would be a clear reason why EditContext couldn't handle those, since it has just text buffer
[17:14] <smaug> smaug: feels like this needs some more investigation
[17:15] <smaug> johanneswilm: so dandclark will work on this more, and explain why each case should be excluded
[17:15] <smaug> dandclark: feedback from other vendors would be good

**Comment by dandclark** [comment]
Going through each inputType defined at https://w3c.github.io/input-events/#interface-InputEvent-Attributes:

| inputType | EditContext currently handles? | EditContext should handle? | Why? |
| ------------- | ------------- | ------------- | ------------- |
|"insertText" | Yes | Yes| Simple text-only operation |
| "insertReplacementText" | No | No | Typically involves other UI like spellcheck |
| "insertLineBreak" | No | No | Can be complex; see [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/insert_line_break_command.cc;l=69;drc=cfdeb0d3f285097244aea65c869f237b0f3320a4). There is e.g. a question of whether to use a `<br>` vs a `‘\n’` and in certain cases extra linebreaks can be inserted.|
| "insertParagraph" | No | No | Complex command, relies on formats ([InsertParagraphSeparatorCommand::DoApply](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/insert_paragraph_separator_command.cc;l=240;drc=cfdeb0d3f285097244aea65c869f237b0f3320a4)). |
| "insertOrderedList" | No | No | Involves non-text content|
| "insertUnorderedList" | No | No | Involves non-text content |
| "insertHorizontalRule" | No | No | Involves non-text content |
| "insertFromYank" | No | No | Involves clipboard/dragdrop |
| "insertFromDrop" | No | No | Involves clipboard/dragdrop |
| "insertFromPaste" | No | No | Involves clipboard/dragdrop |
| "insertFromPasteAsQuotation" | N/A | No | Involves clipboard/dragdop. Also, Chromium doesn’t implement, do other engines support? |
| "insertTranspose" | No | Yes*| *This exists as “transpose” in Chromium. “insertTranspose” doesn’t exist in WebKit, not sure about “transpose”. Neither work in Firefox. |
| "insertCompositionText" | No | No | This event isn’t fired for EditContext |
| "insertLink" | No | No | Involves non-text content |
| "deleteWordBackward" | Yes | Yes | Core text-only editing operation |
| "deleteWordForward" | Yes | Yes | Core text-only editing operation |
| "deleteSoftLineBackward" | No | No | Involves formatting (line breaks) |
| "deleteSoftLineForward" | No | No | Involves formatting (line breaks) |
| "deleteEntireSoftLine" | No | No | Involves formatting (line breaks) |
| "deleteHardLineBackward" | No | No | Involves formatting (line breaks, block breaks) |
| "deleteHardLineForward" | No | No | Involves formatting (line breaks, block breaks) |
| "deleteByDrag" | No | No | Involves clipboard/dragdrop |
| "deleteByCut" | No | No | Involves clipboard/dragdrop |
| "deleteContent" | N/A | Yes? | Not implemented in Chromium. Do other engines implement? |
| "deleteContentBackward" | Yes | Yes | Simple text-only operation|
| "deleteContentForward" | Yes | Yes | Simple text-only operation|
| "historyUndo" | No| No| EditContext doesn’t have undo stack info |
| "historyRedo" | No| No| EditContext doesn’t have undo stack info |
| "formatBold" | No | No | Involves formatting |
| "formatItalic" | No | No | Involves formatting |
| "formatUnderline" | No | No | Involves formatting |
| "formatStrikeThrough" | No | No | Involves formatting |
| "formatSuperscript" | No | No | Involves formatting |
| "formatSubscript" | No | No | Involves formatting |
| "formatJustifyFull" | No | No | Involves formatting |
| "formatJustifyCenter" | No | No | Involves formatting |
| "formatJustifyRight" | No | No | Involves formatting |
| "formatJustifyLeft" | No | No | Involves formatting |
| "formatIndent" | No | No | Involves formatting |
| "formatOutdent" | No | No | Involves formatting |
| "formatRemove" | No | No | Involves formatting |
| "formatSetBlockTextDirection" | No | No | Involves formatting |
| "formatSetInlineTextDirection" | No | No | Involves formatting |
| "formatBackColor" | No | No | Involves formatting |
| "formatFontColor" | No | No | Involves formatting |
| "formatFontName" | No | No | Involves formatting |


For the most part what my analysis of which commands EditContext should support matches what’s already been implemented in Chromium. One exception is “insertTranspose”, which EditContext could support, but the interoperability status of the “insertTranspose” is not clear. It exists under the name “transpose” in Chromium. In WebKit “insertTranspose” doesn’t exist -- not sure about “transpose” – and neither work in Firefox. I guess for browsers that implement it, under whatever name, EditContext should support it.

There's also a caveat about “deleteContent”. This is probably a candidate for EditContext to support, but contrary to my first comment in this thread, that command doesn’t actually exist in Chromium (only "deleteContentForward"/"deleteContentBackward" exist). Looks like Firefox also does not support it, but WebKit maybe does? In any case the spec should probably indicate it as supported by EditContext for browsers who implement the command.
